# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18f1d35cf4681fd817188d059f81495540914692418277734c6b41d41db6fde6a8f5c4272f982e7be3fe13c4348212c29d887012c67ac34c6bedf87cc4908788

test:
  secret_key_base: 5d1ce1e114a9f231a8ca743fefb15f11bcd55f596c8a3fab8ba24210cbcb1dbfe1f6595ea793c7e115d48867f0d25969948874d0516f2c67753e66706d71e665

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
